### ISSUE TITLE
Set a countdown for each week?

### ISSUE THREAD

**Issue by debby1** [icambron/moment-countdown#10]
Hi, can I set a countdown for each week?

For example today is 05 june 2016 --> countdown from 05 june 2016 to 12 june 2016 (-6 days, -5 days etc).

Is it possible with this js?

Thanks

**Comment by icambron** [comment]
Check out [iterate()](http://isaaccambron.com/twix.js/docs.html#iterate) in the [Twix plugin](http://isaaccambron.com/twix.js)
