### ISSUE TITLE
doesnt work on npm

### ISSUE THREAD

**Issue by contra** [icambron/moment-countdown#6]
`require('moment-countdown')` fails with

```
Cannot find module 'twix' from '/Users/contra/Projects/glance/node_modules/moment-countdown/bin'
```

**Comment by icambron** [comment]
Hmm, `moment-countdown` no longer references Twix in any way, and hasn't for years (specifically, since ffc2703fd0b4cc786b414fe70828e0125d5fb113). Are you sure you have the latest version?

**Comment by icambron** [comment]
Just in case, I pushed a new version to NPM, since I've long last track of what was published how.
