### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by Surfoo** [icambron/moment-countdown#9]
Hello,

countdown.js provide [a light localization system](https://github.com/mckamey/countdownjs/#localization), how can we use it for moment-countdown? Do you have an example please?

Thanks!

**Comment by icambron** [comment]
I haven't tried it, but I'd expect it to work out of the box just as it's described in those docs. Have you tried that? Also, are in the browser or Node?

**Comment by RichardLindhout** [comment]
@Surfoo Just put this in your javascript file

countdown.setLabels(
    ' milliseconde| seconde| minuut| uur| dag| week| maand| jaar| decennium| eeuw| millennium',
    ' milliseconden| seconden| minuten| uren| dagen| weken| maanden| jaren| decennia| centuries| millenniums',
    ' and ',
    ', ',
    '',
    function(n){ return n.toString(); });

**Comment by RichardLindhout** [comment]
It's in their documentation as @icambron  said!

**Comment by Surfoo** [comment]
Oh sorry, it worked few hours later my post and I forgot to close it..

**Comment by MaxInMoon** [comment]
How can we access to the `countdown` variable? 

___________

Those imports
```javascript 
import 'moment-countdown';
or
import countdown from 'moment-countdown';
``` 
don't give me access to `countdown`

**Comment by icambron** [comment]
Can't you just import from `'countdown'`?
